In [2]:
num_list = [1,2,3,4,5,6,7,8]

for n in num_list:
    if n % 2 == 0:
        print(n)

2
4
6
8


In [ ]:
# this is called list comprehension. 
the_list=

In [4]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
c = a.reshape(2,-1)
print(c)

[[1 2 3]
 [4 5 6]]


In [8]:
d = c.ravel()
print(c)
# ravel will flatten an array into a 2d array. 

[[1 2 3]
 [4 5 6]]


In [10]:
a = np.arange(10).reshape(5,2)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
f = c.T
print(f)

[[1 4]
 [2 5]
 [3 6]]


In [13]:
g = c.transpose((1,0))
g

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#Indexing:
#a[0,0] top-left element
# a[0,-1] first row, last column
# a[0,:] first row (many entries)
# a[:,0] first column (many enteries)

In [14]:
g[1,1]

5

In [15]:
# Python Slicing
a = list(range(10))
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [20]:
threebythree = np.array(range(2,11)).reshape(3,3)
print(threebythree)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [21]:
np.sqrt(threebythree)

array([[1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766]])

In [ ]:
import pandas as pd

#pd.dataframe(my_list)

